### ISSUE TITLE
Connection provider

### ISSUE THREAD

**Issue by cocowalla** [ahydrax/Hangfire.PostgreSql#10]
This library provides a `UsePostgreSqlStorage` method, which in turn uses `PostgreSqlStorage`, which lets you specify a connection string. However, in order to use client certificates, or specify a custom validation handler for the server certificate, we need access to the actual connect.

Is there any means to specify a connection _provider_, instead of just a connection string? (something like an overloaded `UserPostgresSqlStorage` that takes a `Func<NpgsqlConnection>`)

I thought of quickly fixing this by creating a new class inheriting from `PostgreSqlStorage`, but unfortunately it's marked as `sealed` - is there a reason for that?

**Comment by ahydrax** [comment]
Hi @cocowalla, subtyping from `PostgreSqlStorage` wouldn't solve your problem as it only delegates creation of connections to `IConnectionProvider`.

**Comment by ahydrax** [comment]
Conversation is moved to https://github.com/ahydrax/Hangfire.PostgreSql/pull/11 as you already proposed  a good way to handle it.
