### ISSUE TITLE
Question: Dedicated job queue connection

### ISSUE THREAD

**Issue by cocowalla** [ahydrax/Hangfire.PostgreSql#13]
The original `Hangfire.PostgreSql`, as well as [`Hangfire.SqlServer`](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.SqlServer/SqlServerStorage.cs), both use a dedicated connection for polling the job queue. I was just curious as to why this fork doesn't do that?

**Comment by ahydrax** [comment]
Hi @cocowalla, the idea is about simplifying internal design of job queue. Connection lifetime management is hidden by `IConnectionProvider` now and removed from `JobQueue`.

**Comment by cocowalla** [comment]
Thanks, was just curious :smile:
