### ISSUE TITLE
use bigint for id's

### ISSUE THREAD

**Issue by schmitch** [ahydrax/Hangfire.PostgreSql#14]
currently most id's are integer, which will limit the jobs that can be commited.
better would be to use bigint, especially if people use a lot of recurring jobs.

I actually created a PR for the other project: https://github.com/frankhommers/Hangfire.PostgreSql/pulls

Guess I could also do a PR here.

**Comment by ahydrax** [comment]
Hi @schmitch ! I'll take a look on this.
Do you know if there are any caveats?

**Comment by schmitch** [comment]
well index lookups are a little bit slower of course, but the loss is pretty small on x64
