### ISSUE TITLE
Support for Hangfire 1.7 and netstandard 2.0

### ISSUE THREAD

**Issue by ahydrax** [ahydrax/Hangfire.PostgreSql#16]
Details on hf release: [https://github.com/HangfireIO/Hangfire/releases/tag/v1.7.0](https://github.com/HangfireIO/Hangfire/releases/tag/v1.7.0)

**Comment by ahydrax** [comment]
Pull request: https://github.com/ahydrax/Hangfire.PostgreSql/pull/17

**Comment by ahydrax** [comment]
Includes: #14

**Comment by ahydrax** [comment]
Includes: #12

**Comment by cocowalla** [comment]
Hi, any news on when Hangfire 1.7 support will hit `master`?

In the mean-time, what kind of shape is the the `hf-1.7` branch in?

Thanks!

**Comment by ahydrax** [comment]
Hi @cocowalla, I would say it's nearly finished - I'm still worrying about changing db schema a lot. I would be very thankful for another pair of eyes to review it https://github.com/ahydrax/Hangfire.PostgreSql/pull/17

**Comment by cocowalla** [comment]
AFAICS, the schema changes are all in [Install.v12.sql](https://github.com/ahydrax/Hangfire.PostgreSql/blob/26b3a9d97fc7fef0236963bbb6db9d239af64b45/src/Hangfire.PostgreSql/Schema/Install.v12.sql)?

If so, I don't see anytjhing problematic there. I see you're changing from 32-bit keys to 64-bit keys for some tables, but for `counter` and `hash` it looks like you're moving to `TEXT` keys - I was a little curious about the reasoning?

I had a quick look at the test suite, and it looks like most tests hit a real database, which should increase certainty. But if your tests aren't giving you enough confidence, maybe some more integration/system tests might help, testing the process from end to end?

**Comment by ahydrax** [comment]
@cocowalla yep, changes are in `Install.v12`.

According to documentation `TEXT` and `varchar(n)` use the same datatype internally. But `TEXT` will allow us to have less issues third-party hangfire plugins.

I also would like to improve somehow `Tests.Web` project since now I need to run test scenatious manually.

The only thing I'm worrying about is removing primary key from `hash` and `set`. Not sure if somebody relies on that order. (I tried to use `Hangfire.Console` with new build and it looks ok. )

**Comment by cocowalla** [comment]
The database schema isn't exactly part of the public API, so I wouldn't be too worried myself :)

I noticed the MSSQL plugin also made schema changes for 1.7, just wondered if yours are related?

**Comment by ahydrax** [comment]
@cocowalla nope :) those changes are independent. Made some local optimizations for queueing and monitoring.
