### ISSUE TITLE
Recurring jobs broken schedule

### ISSUE THREAD

**Issue by primez** [ahydrax/Hangfire.PostgreSql#2]
Hello
I've chosen this awesome nuget package to use for our hangfire scheduler, because we already work with PostgresSql. 
I have a recurring job, which should be run once a day. The very first run is ok - it runs as expected, but then something strange starts to happen:
1) `Next execution` on the dashboard is not updated and shows the first run's time.
After second run it gets worse 
2) Hangfire starts to enqueue  a few copies of the job every minute.
Everything is hosted inside ASP.NET Core 2.0 app - so 1 server with 20 workers.  
`[DisableConcurrentExecution(timeoutInSeconds: 1000)]`, `[AutomaticRetry(Attempts = 0)]` are put on the method.
The process is hosted as the docker container.
When the storage is switched to SQL Server - everything works fine.
Any help is appreciated

**Comment by primez** [comment]
Just tried the original package - https://github.com/frankhommers/Hangfire.PostgreSql. It also works fine

**Comment by ahydrax** [comment]
@primez thanks for the bug report, will have a look.

**Comment by primez** [comment]
Thank you

**Comment by ahydrax** [comment]
Fixed in dev branch

**Comment by ahydrax** [comment]
Merged in master. Deployed on nuget

**Comment by primez** [comment]
Cool. Thank you.
