### ISSUE TITLE
Open connections

### ISSUE THREAD

**Issue by dariomalfatti-centropaghe** [ahydrax/Hangfire.PostgreSql#21]
Hi, looking at the open Postgres' connections, seems that Hangfire keep open many connections executing query like these:

```
delete from lock 
where resource = $1

update jobqueue
set fetchedat = $1
where id = (
    select id
    from jobqueue
    where queue IN ('default')
    and (fetchedat is null or fetchedat < $2)
    limit 1
    for update skip locked)
returning id as Id, jobid as JobId, queue as Queue, fetchedat as FetchedAt

update jobqueue
set fetchedat = $1
where id = (
    select id
    from jobqueue
    where queue IN ('default')
    and (fetchedat is null or fetchedat < $2)
    limit 1
    for update skip locked)
returning id as Id, jobid as JobId, queue as Queue, fetchedat as FetchedAt

select distinct queue from jobqueue
```

I have tens of these always open. Is this behavior correct or there is a bug that connections are kept open?

Thank you.

**Comment by ahydrax** [comment]
Hi @dariomalfatti-centropaghe , it's expected behavior: workers poll job queue for new items. If you want to limit open connections there are two options for now:
* set `Maximum Pool Size` parameter in your connection string
* set worker limit inside your hangfire server settings

**Comment by dariomalfatti-centropaghe** [comment]
ok, great, thank you for your reply
