### ISSUE TITLE
Support Npgsql 6

### ISSUE THREAD

**Issue by cocowalla** [ahydrax/Hangfire.PostgreSql#28]
This library currently supports Npgsql `>= 5.0.0 && < 6.0.0` - would be great to support v6.

I'm actually using v6 already, since it's required for another library I'm using, and AFAICT everything still works OK with this library, but of course it means I get a warning like:

```
MyProject.csproj: [NU1608] Detected package version outside of dependency constraint: Hangfire.PostgreSql.ahydrax 1.7.4 requires Npgsql (>= 5.0.0 && < 6.0.0) but version Npgsql 6.0.3 was resolved.
```

**Comment by ahydrax** [comment]
Hi @cocowalla , I was planning to add npgsql6 support for upcoming Hangfire 1.8 release. I'll check out if everything is stable enough if I replace constraint `< 6.0.0` with `< 6.1.0`.

**Comment by ahydrax** [comment]
Done in https://www.nuget.org/packages/Hangfire.PostgreSql.ahydrax/1.7.5 😄
